# Generated by Django 4.1.3 on 2023-01-03 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="name",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="student",
            name="phone_no",
            field=models.CharField(max_length=30),
        ),
    ]
