# Generated by Django 4.1.3 on 2023-01-03 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0003_task"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="task",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
