# Generated by Django 4.1.3 on 2023-01-04 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0004_alter_student_id_alter_task_id"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Task",
        ),
    ]
